# Site settings
title:       CoderDojo BLR
email:       bangalore.in@coderdojo.com
author:      Galaxy Kadiyala
description: "We are a volunteer group based in Bangalore, India teaching kids about web and app development."
baseurl:     ""
url:         "http://coderdojoblr.org"

# Google analytics
google_analytics:

# Optional features
animated:           true
show_related_posts: false
show_post_footers:  true

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: galaxyk

# Social icons
show_social_icons: true
github_username: CoderDojoBLR
stackoverflow_id:
twitter_username: CoderDojoBLR
google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     3
sass:
  compressed: true
gems:
  - jekyll-sitemap
